In [9]:
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from xgboost import XGBRegressor
from sklearn.metrics import f1_score
import yfinance as yf
from pprint import pprint

# Data Import

In [10]:
df = yf.download("AAPL", start="2020-01-01", end="2024-12-31")
df = df[['Open', 'High', 'Low', 'Close', 'Volume']]
df.tail()

[*********************100%***********************]  1 of 1 completed

Price             Open        High         Low       Close    Volume
Ticker            AAPL        AAPL        AAPL        AAPL      AAPL
Date
2024-12-23  253.385834  254.261043  252.072998  253.883118  40858800
2024-12-24  254.101927  256.807136  253.903002  256.797211  23234700
2024-12-26  256.787255  258.686881  256.230300  257.612732  27237100
2024-12-27  256.429206  257.294505  251.685132  254.201385  42355300
2024-12-30  250.859639  252.122744  249.387684  250.829803  35557500

# Questions

## 1.
Create new features:
- `lag_1`: 1-day lag of the opening price.
- `ma_5`: 5-day moving average of the opening price.
- `ma_10`: 10-day moving average of the opening price.
- `ma_20`: 20-day moving average of the opening price.
- `sd_5`: 5-day standard deviation of the opening price.
- `sd_10`: 10-day standard deviation of the opening price.
- `sd_20`: 20-day standard deviation of the opening price.

In [11]:
df_model = pd.DataFrame(
    {
        "lag_1": df['Open'].shift(1).values[:, 0],
        "ma_5": df['Open'].rolling(window=5).mean().values[:, 0],
        "ma_10": df['Open'].rolling(window=10).mean().values[:, 0],
        "ma_20": df['Open'].rolling(window=20).mean().values[:, 0],
        "sd_5": df['Open'].rolling(window=5).std().values[:, 0],
        "sd_10": df['Open'].rolling(window=10).std().values[:, 0],
        "sd_20": df['Open'].rolling(window=20).std().values[:, 0],
    },
    index=df.index
)
df_model["target"] = df["Open"].values[:, 0] - df_model["lag_1"]
df_model["target"] = df_model["target"].apply(lambda x: 1 if x > 0 else -1)
df_model.dropna(inplace=True)
df_model

,lag_1,ma_5,ma_10,ma_20,sd_5,sd_10,sd_20,target
Date,,,,,,,,
2020-01-30,78.209915,76.553874,76.449016,74.891325,1.448520,1.020967,2.216845,-1
2020-01-31,77.267393,76.586659,76.625951,75.188906,1.468446,1.009200,2.122345,1
2020-02-03,77.361405,76.308966,76.337410,75.275083,1.955278,1.449047,2.001761,-1
2020-02-04,73.352688,76.439615,76.292090,75.534456,1.896406,1.451875,1.708629,1
2020-02-05,76.006676,76.394780,76.411171,75.819865,1.846071,1.543635,1.609859,1
...,...,...,...,...,...,...,...,...
2024-12-23,246.692406,249.148975,247.657122,242.318787,2.992637,2.568257,6.553102,1
2024-12-24,253.385834,250.225099,248.512450,243.513759,3.687212,3.147089,6.404761,1
2024-12-26,254.101927,251.424550,249.529893,244.750006,4.741611,3.995127,6.463999,1
2024-12-27,256.787255,253.479326,250.617951,245.911659,4.065182,4.263029,6.365223,-1
2024-12-30,256.429206,254.312772,251.056556,246.777928,2.420235,4.007212,5.740345,-1

## 2.
Split the dataset into training and testing sets, using the first 70% of the data for training, 20% for validation, and the remaining 10% for testing.

In [12]:
df_train, df_test = train_test_split(df_model, test_size=0.3, shuffle=False)
df_val, df_test = train_test_split(df_test, test_size=0.33, shuffle=False)
df_model.shape, df_train.shape, df_val.shape, df_test.shape

((1238, 8), (866, 8), (249, 8), (123, 8))

## 3.

### 3.1
Train a random forest classifier model to predict whether the opening price will increase or decrease the next day, using the created features as input. Tune the hyperparameters of the model:
- `n_estimators`
- `max_depth`
- `min_samples_split`
- `min_samples_leaf`
- `max_features`

:::{.callout-tip}
Use the `RandomForestRegressor` class from the `sklearn.ensemble` module to train the model, the `GridSearchCV` class from the `sklearn.model_selection` module for cross-validation.
:::

In [13]:
hyperparams = {
    'n_estimators': [10, 30, 50],
    'max_depth': [1, 3, 5],
    'min_samples_leaf': [1, 5, 10],
    'min_samples_split': [10, 20, 50],
    'max_features': [5, 'sqrt', 'log2']
}

In [14]:
idx_train = [i for i in range(df_train.shape[0])]
idx_val = [i for i in range(df_train.shape[0], df_train.shape[0] + df_val.shape[0])]
idx_train[-1], idx_val[0], idx_val[-1]

(865, 866, 1114)

In [15]:
df_cv = pd.concat([df_train, df_val], axis=0)
df_cv.shape

(1115, 8)

In [16]:
cv = GridSearchCV(
    estimator=RandomForestClassifier(),
    param_grid=hyperparams,
    cv=[(idx_train, idx_val)],
    scoring='f1',
)
cv

GridSearchCV(cv=[([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                   18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, ...],
                  [866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877,
                   878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889,
                   890, 891, 892, 893, 894, 895, ...])],
             estimator=RandomForestClassifier(),
             param_grid={'max_depth': [1, 3, 5],
                         'max_features': [5, 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 5, 10],
                         'min_samples_split': [10, 20, 50],
                         'n_estimators': [10, 30, 50]},
             scoring='f1')

In [17]:
cv.fit(df_cv.drop('target', axis=1), df_cv['target'])

GridSearchCV(cv=[([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
                   18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, ...],
                  [866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877,
                   878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889,
                   890, 891, 892, 893, 894, 895, ...])],
             estimator=RandomForestClassifier(),
             param_grid={'max_depth': [1, 3, 5],
                         'max_features': [5, 'sqrt', 'log2'],
                         'min_samples_leaf': [1, 5, 10],
                         'min_samples_split': [10, 20, 50],
                         'n_estimators': [10, 30, 50]},
             scoring='f1')

In [22]:
pd.DataFrame(cv.cv_results_)

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_max_features,param_min_samples_leaf,param_min_samples_split,param_n_estimators,params,split0_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008988,0.0,0.001808,0.0,1,5,1,10,10,"{'max_depth': 1, 'max_features': 5, 'min_sampl...",0.501931,0.501931,0.0,40
1,0.015214,0.0,0.001764,0.0,1,5,1,10,30,"{'max_depth': 1, 'max_features': 5, 'min_sampl...",0.126761,0.126761,0.0,196
2,0.023497,0.0,0.002483,0.0,1,5,1,10,50,"{'max_depth': 1, 'max_features': 5, 'min_sampl...",0.089552,0.089552,0.0,204
3,0.005251,0.0,0.001170,0.0,1,5,1,20,10,"{'max_depth': 1, 'max_features': 5, 'min_sampl...",0.501931,0.501931,0.0,40
4,0.014273,0.0,0.001550,0.0,1,5,1,20,30,"{'max_depth': 1, 'max_features': 5, 'min_sampl...",0.578073,0.578073,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,0.017622,0.0,0.001639,0.0,5,log2,10,20,30,"{'max_depth': 5, 'max_features': 'log2', 'min_...",0.442553,0.442553,0.0,76
239,0.028854,0.0,0.002265,0.0,5,log2,10,20,50,"{'max_depth': 5, 'max_features': 'log2', 'min_...",0.085714,0.085714,0.0,206
240,0.006264,0.0,0.001201,0.0,5,log2,10,50,10,"{'max_depth': 5, 'max_features': 'log2', 'min_...",0.376238,0.376238,0.0,115
241,0.017351,0.0,0.001661,0.0,5,log2,10,50,30,"{'max_depth': 5, 'max_features': 'log2', 'min_...",0.242424,0.242424,0.0,165
242,0.028224,0.0,0.002125,0.0,5,log2,10,50,50,"{'max_depth': 5, 'max_features': 'log2', 'min_...",0.198758,0.198758,0.0,179

In [27]:
cv.best_params_

{'max_depth': 1,
 'max_features': 'sqrt',
 'min_samples_leaf': 5,
 'min_samples_split': 50,
 'n_estimators': 10}

### 3.2
Evaluate the performance of the model using appropriate metrics.

In [23]:
f1_score(df_test['target'], cv.predict(df_test.drop('target', axis=1)))

0.5780346820809249

## 4.

### 4.1.
Train a gradient boosting tree classifier model to predict whether the opening price will increase or decrease the next day, using the created features as input. Tune the hyperparameters of the model:
- `n_estimators`
- `learning_rate`
- `max_depth`
- `subsample`

:::{.callout-tip}
Use the 'GradientBoostingClassifier' class from the 'sklearn.ensemble' module to train a gradient boosting classifier model, and compare its performance with the random forest model.
:::

### 4.2
Evaluate the performance of the model using appropriate metrics.